as2/config/routes.rb
As2::Application.routes.draw do
  resources :blogs

  resources :events2s

  resources :events

end

as2/app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :Message, :Title
end

as2/app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :osc
end

as2/app/models/events2.rb
class Events2 < ActiveRecord::Base
  attr_accessible :Event, :Message
end

as2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

as2/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

as2/app/controllers/events2s_controller.rb
class Events2sController < ApplicationController
  # GET /events2s
  # GET /events2s.json
  def index
    @events2s = Events2.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events2s }
    end
  end

  # GET /events2s/1
  # GET /events2s/1.json
  def show
    @events2 = Events2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @events2 }
    end
  end

  # GET /events2s/new
  # GET /events2s/new.json
  def new
    @events2 = Events2.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @events2 }
    end
  end

  # GET /events2s/1/edit
  def edit
    @events2 = Events2.find(params[:id])
  end

  # POST /events2s
  # POST /events2s.json
  def create
    @events2 = Events2.new(params[:events2])

    respond_to do |format|
      if @events2.save
        format.html { redirect_to @events2, notice: 'Events2 was successfully created.' }
        format.json { render json: @events2, status: :created, location: @events2 }
      else
        format.html { render action: "new" }
        format.json { render json: @events2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events2s/1
  # PUT /events2s/1.json
  def update
    @events2 = Events2.find(params[:id])

    respond_to do |format|
      if @events2.update_attributes(params[:events2])
        format.html { redirect_to @events2, notice: 'Events2 was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @events2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events2s/1
  # DELETE /events2s/1.json
  def destroy
    @events2 = Events2.find(params[:id])
    @events2.destroy

    respond_to do |format|
      format.html { redirect_to events2s_url }
      format.json { head :no_content }
    end
  end
end

as2/app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

as2/app/helpers/application_helper.rb
module ApplicationHelper
end

as2/app/helpers/blogs_helper.rb
module BlogsHelper
end

as2/app/helpers/events2s_helper.rb
module Events2sHelper
end

as2/app/helpers/events_helper.rb
module EventsHelper
end

as2/app/views/blogs/_form.html.erb
<%= form_for @blog, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :Title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Message, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                blogs_path, :class => 'btn' %>
  </div>
<% end %>

as2/app/views/blogs/edit.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

as2/app/views/blogs/index.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:Title) %></th>
      <th><%= model_class.human_attribute_name(:Message) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.id, blog_path(blog) %></td>
        <td><%= blog.Title %></td>
        <td><%= blog.Message %></td>
        <td><%=l blog.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_blog_path(blog), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      blog_path(blog),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_blog_path,
            :class => 'btn btn-primary' %>

as2/app/views/blogs/new.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

as2/app/views/blogs/show.html.erb
<%- model_class = Blog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:Title) %>:</strong></dt>
  <dd><%= @blog.Title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:Message) %>:</strong></dt>
  <dd><%= @blog.Message %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              blogs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_blog_path(@blog), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              blog_path(@blog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

as2/app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :osc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :osc, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

as2/app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

as2/app/views/events/index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:osc) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.osc %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

as2/app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

as2/app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:osc) %>:</strong></dt>
  <dd><%= @event.osc %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

as2/app/views/events2s/_form.html.erb
<%= form_for(@events2) do |f| %>
  <% if @events2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@events2.errors.count, "error") %> prohibited this events2 from being saved:</h2>

      <ul>
      <% @events2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Event %><br />
    <%= f.text_field :Event %>
  </div>
  <div class="field">
    <%= f.label :Message %><br />
    <%= f.text_field :Message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

as2/app/views/events2s/edit.html.erb
<h1>Editing events</h1>

<%= render 'form' %>

<%= link_to 'Show', @events2 %> |
<%= link_to 'Back', events2s_path %>

as2/app/views/events2s/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events2s.each do |events2| %>
  <tr>
    <td><%= events2.Event %></td>
    <td><%= events2.Message %></td>
    <td><%= link_to 'Show', events2 %></td>
    <td><%= link_to 'Edit', edit_events2_path(events2) %></td>
    <td><%= link_to 'Destroy', events2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_events2_path %>

as2/app/views/events2s/new.html.erb
<h1>New events2</h1>

<%= render 'form' %>

<%= link_to 'Back', events2s_path %>

as2/app/views/events2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @events2.Event %>
</p>

<p>
  <b>Message:</b>
  <%= @events2.Message %>
</p>


<%= link_to 'Edit', edit_events2_path(@events2) %> |
<%= link_to 'Back', events2s_path %>

as2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oval Ski Club | Index</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href="app/assets/stylesheets/mycustomcss.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- this section initiates the java to allow my site to respond to different screen sizes -->
    <link href="app/assets/stylesheets/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!-- this is my main section within the navbar, it contains all the page navigation links -->
          <a class="brand" href="blogs" title="Return to Home Page">Oval Ski Club</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="index.html" accesskey="h" title="Home Page"><i class="icon-home icon-inverse"></i><em>H</em>ome</a></li>
              <li><a href="about.html" accesskey="a" title="About us"><em>A</em>bout</a></li>
               <!--<li><a href="contact.html" accesskey="1" title="Contact Us" >Get In Touch!</a></li> -->
              <li><a class="active" href="club_holiday.html" title="Social Events & Club Holiday" accesskey="s">Get <em>S</em>ocial!</a></li>
            
              </li>
              <!-- this is my dropdown box within my navbar -->
               <li class="dropdown">
                <a  href="#" class="dropdown-toggle" data-toggle="dropdown" accesskey="i" title="FAQ & Information">FAQ & <em>I</em>nformation <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="faq.html" accesskey="q" title="FAQ Page" >FA<em>Q</em>s</a></li>
                  <li><a href="clubsessions.html" title="Information on the sessions we run!" accesskey="c"><em>C</em>lub Sessions</a></li>
                  <li><a href="racingteam.html" title="Our superb racing team!" accesskey="o"><em>O</em>ur Racing Team</a></li>
                  <li class="divider"></li>
                  <li><a href="accesskeyinfo.html" title="information on how to use access keys" accesskey="l"><em>L</em>ist of Access Keys</a></li>
                  </ul>
            </ul>
            <!-- this displays the sign in sction on the right hand side of the navbar -->
            <form class="navbar-form pull-right" action="index.html">
              <input class="span2" type="text" title="Please Enter Your Email Address" placeholder="Email">
              <input class="span2" type="password" title="Please Enter Your Password" placeholder="Password">
              <button <input type="submit" value="Submit" title="Sign In">Sign in</button>
            </form>
           
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

    
    <!-- Hero unit, this contains the welcome message to the page, an image and link to provide more information about the club -->
      <div class="hero-unit">
        <h1>Welcome to Oval Ski Club!</h1>
        <p>Located in Bebington on the Wirral, We offer skiing tuition for all ages, an active social club promoting various events through out the year, and also a Ski Racing Team which all members are welcome to join. We are ideally located for the Wirral, Cheshire, Liverpool and Merseyside areas.
        </p>
        <p><a class="btn btn-primary btn-large" href="about.html" title="About Us">More Information &raquo;</a></p>
      </div>

      <div class="span4 pull-right" style="max-height:700px; overflow-y:scroll;">
      <h3>Upcoming Social Events</h3>
      <p> For more information about these events, please see the <a href="club_holiday.html" title="More information on social events"> Social Events page.</a></p>

         <i class="icon-calendar"></i>
            <strong>Sunday 18/11/12</strong>
            <p>Yellow Duckmarine
              <br>
              11.30AM
              <br>
              </p>
                   

          <i class="icon-calendar"></i>
            <strong>Wednesday 23/01/13</strong>
            <p>5.00pm - 8.00pm
              <br>
              Getting Nailed
              <br></P>
              
          <i class="icon-calendar"></i>
            <strong>Saturday 23/03/13-30/03/13</strong>
            <br><p>
            All Week
            <br>
            St.Christoph/St.Anton Ski Holiday
            <br></p>

            <i class="icon-calendar"></i>
            <strong>Sunday 15/07/13</strong>
            <br><p>
            17:00
            <br>
            Club AGM
            <br></p>

              <i class="icon-calendar"></i>
            <strong>Saturday 13/08/13</strong>
            <br><p>
            13:00-all day
            <br>
            Walk to Hilbre Island
            <br></p>

             
                     
          </div>

      <!-- this section contains the information that is displayed on the main part of the webpage -->
      <div class="row">
        <div class="span7">
          <h2>Closed for Summer</h2>
          <p>The 2011/2012 season has now finished. We will be busy over the summer months maintaining the slope so we are ready to open in September for next season. Check the sessions page for when we will be open and when we start new beginner lessons. See you then! </p>
          
        </div>
        <div class="span8">
          <h2>Never skied before? Don't let this stop you joining the club!</h2>
          <p>We provide lessons through out the season to all of our club members including people who have never skied before. For complete beginners these blocks of lessons start approx. every three weeks - see list below for starting dates. So if you are new to skiing and interested in joining the club then just turn up early on the starting date to enrole! See our club sessions page for more information.</p>
          
          <p>
            

          <p><a class="btn btn-primary btn-small" href="clubsessions.html" title="View Session Information">Click here for more info &raquo;</a></p>
       </div>
        <div class="span7">
          <h2>Interested in a Club that sends its members on holiday? Look no further!</h2>
          <p>Each season the club organises a holiday to one of the popular resorts in Europe. The holiday is arranged over the Easter break making it available to all club members. The group size varies each year, based on flight availability and what the demand is expected to be, and can be anything from 50 - 100 people. Details of this seasons holiday can be found by clicking the following link!</p>
          <p><a class="btn btn-primary btn-small" href="club_holiday.html" title="Holiday Info">Club Holiday Info! &raquo;</a></p>

          <%= yield %>  
        </div>
      </div>

      <hr>

        <!-- this places a footer at the bottom of the page, it contains the "Copyright" and the Connect to facebook link -->
       <footer>
        <p>&copy; Oval Ski Club 2012 &nbsp<center><i class="icon-thumbs-up"></i><a href="http://www.facebook.com/group.php?gid=2256597544">Find and Like us on Facebook!</center></a></p>
      </footer>

    </div> <!-- /container -->

    
    <!-- ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- added new jquery files to allow for JS actions, for dropdown actions and other java actions -->
    <script text/javascript src="assets/js/jquery-1.8.2.min.js"></script>
    <script text/javascript src="assets/js/bootstrap.min.js"></script>


     
 

  </body>
</html>